apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${K8S_NAMESPACE}
  name: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${APP_NAME}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${APP_NAME}
    spec:
      volumes:
        - name: nginx
          configMap:
            name: nginx
            items:
              - key: default.conf
                path: default.conf
            defaultMode: 420
      containers:
        - image: ${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${APP_NAME}:${GIT_TAG}
          imagePullPolicy: Always
          name: ${APP_NAME}
          ports:
          - containerPort: ${APP_PORT}
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: '0.5'
              memory: 1Gi
          volumeMounts:
            - name: nginx
              readOnly: true
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

